# Deployment pipeline documentation: https://docs.ffdcdev.fusionoperate.io/docs/software_factory/deployment_pipelines/

resources:
  repositories:
  - repository: templates
    type: git
    name: FusionOperate/pipeline_templates
    ref: refs/heads/master
  pipelines:
  - pipeline: Build  # This name is referenced in the templates, don't change it
    source: tradecomm-invoice  # source pipeline definition name
    branch: feature/bdd-tests-workshop  # branch to pick the artifact, optional; defaults to all branches
    # version: $(BuildNumber) # pipeline run number to pick artifact; optional; defaults to last successfully completed run
    trigger:     # Optional; Triggers are not enabled by default.
      branches:
        include:  # branches to consider the trigger events, optional; defaults to all branches.
        - develop

trigger: none

stages:
- template: tmpl/fusionfabric/tradecomm/release-develop.yml@templates
  parameters:
    additionalVariables:
      __default__:
        HelmInstallParams: |
          --set spring.datasource.url='jdbc:sqlserver://$(AzureSqlServerUrl);databaseName=tradecomm_poc'
          --set spring.datasource.username='$(AzureSqlServerUser)'
          --set spring.datasource.password='$(AzureSqlServerPassword)'
        HelmTestParams: