#__          __              _             _
#\ \        / /             (_)           | |
# \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _| |
#  \ \/  \/ / _` | '__| '_ \| | '_ \ / _` | |
#   \  /\  / (_| | |  | | | | | | | | (_| |_|
#    \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, (_)
#                                     __/ |
#                                    |___/
# Below you have example of how to define global ingress for microservice which use internal (.io) domain.
# For public domain (.cloud) you should request Traffic Manager from FO team.
# You probably do not need to configure global ingress if your app is region-specific.
# Please consult that with your Architect.
#
ingresses:
  global:
    hosts:
      - tradecomm-invoice-global
    extraIngressAnnotations:
      kubernetes.io/skip-dns-registration: "true"

deployments:
  app:
    docker:
      image: tradecomm/tradecomm-invoice
      tag: __DOCKER_TAG__
    replicas: 1
    extraSecretItems:
    - name: application-properties
      key: application.properties
      path: application.properties
      mountPath: /config
      readOnly: true
    memory:
      limits: 500Mi
      request: 300Mi
    cpu:
      limits: 1000m
      request: 30m

extraSecrets:
  application.properties: |-
    ffdc.chassis.httpLogging.enabled=true
    ffdc.chassis.httpLogging.includeHeaders=false
    ffdc.chassis.httpLogging.includePayload=true
    ffdc.chassis.httpLogging.includeQueryString=true
    ffdc.chassis.httpLogging.maxPayloadLength=10000

tests:
  acceptance:
    tags: ''

test:
  pods:
  - docker:
      image: tradecomm/test/tradecomm-invoice-acceptance
      tag: __DOCKER_TAG__
    extraEnvs:
      - name: CUCUMBER_FILTER_TAGS
        value: "{{ .Values.tests.acceptance.tags }}"
    extraAnnotations:
   #   type: acceptance|ci
   #   platform: cucumber
   # args: ["--threads","2"]
#  - docker:
#      image: tradecomm/test/tradecomm-invoice-performance
#      tag: __DOCKER_TAG__
#    hookWeight: "1"
#    extraEnvs:
#    - name: TOKEN
#      value: "1234567890"
#    extraAnnotations:
#      type: performance|ci
#      platform: gatling
#    args:
#    - "{{ printf \"-%s\" .Values.test.envName }}"
#    - scenarios.yml
#    - perf-smoke.yml
#  - docker:
#      image: tradecomm/test/tradecomm-invoice-performance
#      tag: __DOCKER_TAG__
#    hookWeight: "2"
#    hookTimeout: 20m
#    extraEnvs:
#      - name: TOKEN
#        value: "1234567890"
#    extraAnnotations:
#      type: performance
#      platform: gatling
#    args: ["scenarios.yml", "perf-regression.yml"]
